---
languageCode: "en-gb"
title: "madoni.us"
baseurl: "https://madoni.us/"
theme: "hugo-material-docs"
metadataformat: "yaml"
canonifyurls: true
# Enable Google Analytics by entering your tracking id
# googleAnalytics: ""

params:
  author: "madonius"
  description: "A site about madonius"
  copyright: "Released under CC-BY-NC 4.0"

  # Repository
  # provider = "GitHub"
  # repo_url = "https://github.com/digitalcraftsman/hugo-material-docs"

  #version = "1.0.0"
  logo: "images/favicon.png"
  favicon: "images/favicon.png"

  permalink: "#"

  # Custom assets
  custom_css: []
  custom_js: []
  # Syntax highlighting theme
  highlight_css: ""
  palette:
    primary: "light-blue"
    accent: "light-purple"
  font:
    text: "Ubuntu"
    code: "Ubuntu Mono"

social:
  twitter: "madonius"
  github: "madonius"
  email: "web@kampitakis.de"

menu:
  main:
    - name: "About"
      weight: 0
    - name: "Crypto"
      identifier: 'crypto'
      url: "crypto"
      weight: 10
    - name: "PGP"
      parent: 'crypto'
      url: "crypto/pgp"
      weight: 10
    - name: "Threema"
      parent: "crypto"
      url: "crypto/threema"
      weight: 20
    - name: "Imprint"
      url: "impressum"
      weight: 1000

taxonomies:
  tag: "tags"

blackfriday:
  smartypants: true
  fractions: true
  smartDashes: true
  plainIDAnchors: true
